# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ vars.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore back-end/src/API/SPA.Api/SPA.Api.csproj
      
    - name: Build
      run: dotnet build back-end/src/API/SPA.Api/SPA.Api.csproj --no-restore


  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Test
      run: dotnet test back-end/test/SPA.Test/SPA.Test.csproj --logger "console;verbosity=detailed"


  docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Setup docker build
      uses: docker/setup-buildx-action@v3.6.1

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: hygorluis
        password: 3ky09p000

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.7.0
      with:
        context: ./back-end
        file: ./Dockerfile
        push: true
        tags: hygorluis/back-end:${{ github.ref_name }}
          

          
