name: Test Environment Variables

on: [push]

jobs:
  test-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "MY_VAR1=Hello World" >> $GITHUB_ENV
          echo "MY_VAR2=12345" >> $GITHUB_ENV

      - name: Print environment variables
        run: |
          echo "MY_VAR1: $MY_VAR1"
          echo "MY_VAR2: $MY_VAR2"
