name: Test Environment Variables

on: [push]

jobs:
  test-env:
    runs-on: ubuntu-latest
    environment: CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print environment variable
        run: |
          echo "DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}"
