name: Entrega continua

on:
  workflow_call:

jobs:

  Deploy:
    runs-on: ubuntu-latest
    environment: SPA

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /home/${{ secrets.REMOTE_USER }}
        SOURCE: /.github/workflows/docker-compose.yml

    - name: Executing remote ssh commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo mv /home/${{ secrets.REMOTE_USER }}/docker-compose.yml /root/
          sudo systemctl start docker
          sudo docker compose down
          sudo docker compose pull
          sudo docker compose up -d
