name: Entrega continua

on:
  workflow_call:

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: SPA

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /home/${{ secrets.REMOTE_USER }}
        SOURCE: docker-compose.yml

    - name: Executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/${{ secrets.REMOTE_USER }}
          sudo systemctl start docker
          docker-compose down
          docker-compose pull
          docker-compose up -d
