name: Angular

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ vars.NODE_VERSION }}
      
    - name: Install Angular dependencies
      working-directory: front-end
      run: npm install

    - name: Build Angular project
      working-directory: front-end
      run: npm run build


  docker:
    needs: build
    runs-on: ubuntu-latest
    environment: CI

    steps:
    - uses: actions/checkout@v4
      
    - name: Setup docker build
      uses: docker/setup-buildx-action@v3.6.1

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.7.0
      with:
        context: ./front-end
        file: front-end/Dockerfile
        push: true
        tags: hygorluis/front-end:${{ github.ref_name }}
