name: Angular

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ vars.NODE_VERSION }}
      
    - name: Install Angular dependencies
      working-directory: front-end
      run: npm install

    - name: Build Angular project
      working-directory: front-end
      run: npm run build
