name: SPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  back-end:
    uses: ./.github/workflows/back-end.yml

  front-end:
    uses: ./.github/workflows/front-end.yml
