name: SPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Back-end:
    uses: ./.github/workflows/back-end.yml
    secrets: inherit

  Front-end:
    uses: ./.github/workflows/front-end.yml
    secrets: inherit

  EC2:
    needs: [Back-end, Front-end]
    uses: ./.github/workflows/EC2.yml
    secrets: inherit
