name: SPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  back-end:
    uses: ./.github/workflows/back-end.yml
    secrets: inherit

  front-end:
    uses: ./.github/workflows/front-end.yml
    secrets: inherit

  deploy_EC2:
    uses: ./.github/workflows/EC2.yml
    secrets: inherit
