name: Test Secrets
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo secrets
        run: |
          echo "USERNAME: ${{ vars.DOCKERHUB_USERNAME }}"
          echo "PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}"
